fix gitub action

diff --git a/.github/workflows/lza.yml b/.github/workflows/lza.yml
--- a/.github/workflows/lza.yml
+++ b/.github/workflows/lza.yml
@@ -8,9 +8,9 @@ jobs:
     build:
         runs-on: ubuntu-latest
         permissions:
-          security-events: write
-          actions: read
-          contents: read        
+            security-events: write
+            actions: read
+            contents: read
         steps:
             - uses: actions/checkout@v3
               with:
@@ -28,7 +28,7 @@ jobs:
             - name: compile
               run: yarn compile
             - name: lza_review 02-spoke
-              run: node packages/cli/built/gptools.js run lza_review applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/02-spoke/deploy.spoke.bicep -ot $GITHUB_STEP_SUMMARY -l "review of 02-spoke -oa spoke.sarif"
+              run: node packages/cli/built/gptools.js run lza_review applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/02-spoke/deploy.spoke.bicep -ot $GITHUB_STEP_SUMMARY -l "review of 02-spoke" -oa spoke.sarif
               env:
                   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                   OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
@@ -37,22 +37,22 @@ jobs:
               if: success() || failure() # run this step even if previous step failed
               uses: github/codeql-action/upload-sarif@v3
               with:
-                sarif_file: spoke.sarif
+                  sarif_file: spoke.sarif
             - name: lza_review all
-              run: node packages/cli/built/gptools.js run lza_review applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/**/deploy.*.bicep -ot $GITHUB_STEP_SUMMARY -l "review of scenarios"
+              run: node packages/cli/built/gptools.js run lza_review applications/lza/aca-landing-zone-accelerator/scenarios/aca-internal/bicep/modules/**/deploy.*.bicep -ot $GITHUB_STEP_SUMMARY -l "review of scenarios" -oa all.sarif
               env:
                   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                   OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                   OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
+            - name: Upload SARIF file
+              if: success() || failure() # run this step even if previous step failed
+              uses: github/codeql-action/upload-sarif@v3
+              with:
+                  # Path to SARIF file relative to the root of the repository
+                  sarif_file: all.sarif
             - name: lza_review test
               run: yarn test:lza
               env:
                   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                   OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
                   OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
-            - name: Upload SARIF file
-              if: success() || failure() # run this step even if previous step failed
-              uses: github/codeql-action/upload-sarif@v3
-              with:
-                # Path to SARIF file relative to the root of the repository
-                sarif_file: results.sarif
